<?xml version="1.0" encoding="UTF-8"?>
<testng-results retried="2" ignored="0" total="4" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2025-05-23T17:20:15 IST" name="Default suite" finished-at="2025-05-23T17:20:23 IST" duration-ms="8497">
    <groups>
      <group name="negative">
        <method signature="LoginDDT.logintest_002_valid_email_invalid_pass(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" name="logintest_002_valid_email_invalid_pass" class="wm.TestCases.LoginDDT"/>
      </group> <!-- negative -->
    </groups>
    <test started-at="2025-05-23T17:20:15 IST" name="Default test" finished-at="2025-05-23T17:20:23 IST" duration-ms="8497">
      <class name="wm.TestCases.LoginDDT">
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:16 IST" name="launchApplication" finished-at="2025-05-23T17:20:18 IST" duration-ms="1942" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="logintest_002_valid_email_invalid_pass(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:18 IST" name="logintest_002_valid_email_invalid_pass" data-provider="LoginData" finished-at="2025-05-23T17:20:18 IST" duration-ms="6" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestCase001- Valid user name and password.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Positive]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nikhil10]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bcil@12345678]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Â©2025-2026 Bar Code India Limited. All rights reserved.]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest_002_valid_email_invalid_pass -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:18 IST" name="closeBrowser" finished-at="2025-05-23T17:20:18 IST" duration-ms="172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:18 IST" name="launchApplication" finished-at="2025-05-23T17:20:19 IST" duration-ms="1154" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="logintest_002_valid_email_invalid_pass(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:19 IST" name="logintest_002_valid_email_invalid_pass" data-provider="LoginData" finished-at="2025-05-23T17:20:19 IST" duration-ms="529" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestCase002-Valid user name and invalid password.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Negative]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nikhil10]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bcil@987654321]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Invalid username or password!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid username or password!] but found [Maximum login attempt reached, user locked out, please contact admin to reset the password!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid username or password!] but found [Maximum login attempt reached, user locked out, please contact admin to reset the password!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at wm.TestCases.LoginDDT.logintest_002_valid_email_invalid_pass(LoginDDT.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:230)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:63)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest_002_valid_email_invalid_pass -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:19 IST" name="closeBrowser" finished-at="2025-05-23T17:20:20 IST" duration-ms="149" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:20 IST" name="launchApplication" finished-at="2025-05-23T17:20:21 IST" duration-ms="1172" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method retried="true" signature="logintest_002_valid_email_invalid_pass(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:21 IST" name="logintest_002_valid_email_invalid_pass" data-provider="LoginData" finished-at="2025-05-23T17:20:21 IST" duration-ms="511" status="SKIP">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestCase002-Valid user name and invalid password.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Negative]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nikhil10]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bcil@987654321]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Invalid username or password!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid username or password!] but found [Maximum login attempt reached, user locked out, please contact admin to reset the password!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid username or password!] but found [Maximum login attempt reached, user locked out, please contact admin to reset the password!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at wm.TestCases.LoginDDT.logintest_002_valid_email_invalid_pass(LoginDDT.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest_002_valid_email_invalid_pass -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:21 IST" name="closeBrowser" finished-at="2025-05-23T17:20:21 IST" duration-ms="191" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
        <test-method is-config="true" signature="launchApplication()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:21 IST" name="launchApplication" finished-at="2025-05-23T17:20:23 IST" duration-ms="1135" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- launchApplication -->
        <test-method signature="logintest_002_valid_email_invalid_pass(java.lang.String,java.lang.String,java.lang.String,java.lang.String,java.lang.String)[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:23 IST" name="logintest_002_valid_email_invalid_pass" data-provider="LoginData" finished-at="2025-05-23T17:20:23 IST" duration-ms="480" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[TestCase002-Valid user name and invalid password.]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Negative]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Nikhil10]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Bcil@987654321]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[Invalid username or password!]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [Invalid username or password!] but found [Maximum login attempt reached, user locked out, please contact admin to reset the password!]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [Invalid username or password!] but found [Maximum login attempt reached, user locked out, please contact admin to reset the password!]
at org.testng.Assert.fail(Assert.java:111)
at org.testng.Assert.failNotEquals(Assert.java:1590)
at org.testng.Assert.assertEqualsImpl(Assert.java:150)
at org.testng.Assert.assertEquals(Assert.java:132)
at org.testng.Assert.assertEquals(Assert.java:656)
at org.testng.Assert.assertEquals(Assert.java:666)
at wm.TestCases.LoginDDT.logintest_002_valid_email_invalid_pass(LoginDDT.java:27)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:687)
at org.testng.internal.invokers.TestInvoker.retryFailed(TestInvoker.java:269)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:76)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:995)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:203)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:154)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:134)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:741)
at org.testng.TestRunner.run(TestRunner.java:616)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:421)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:413)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:373)
at org.testng.SuiteRunner.run(SuiteRunner.java:312)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1274)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1208)
at org.testng.TestNG.runSuites(TestNG.java:1112)
at org.testng.TestNG.run(TestNG.java:1079)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logintest_002_valid_email_invalid_pass -->
        <test-method is-config="true" signature="closeBrowser()[pri:0, instance:wm.TestCases.LoginDDT@76b07f29]" started-at="2025-05-23T17:20:23 IST" name="closeBrowser" finished-at="2025-05-23T17:20:23 IST" duration-ms="163" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- wm.TestCases.LoginDDT -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
